# Generated by Django 4.1.3 on 2022-11-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='district',
            new_name='district_name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state',
            new_name='state_name',
        ),
    ]
